[package]
name = "renderer-windows"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
libterm = { path = "../libterm" }
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
