[package]
name = "tf"
description = "TermForge command-line companion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tf-shell.workspace = true
tf-proto.workspace = true
tf-ipc = { path = "../../crates/tf-ipc" }
anyhow.workspace = true
clap.workspace = true
tokio = { version = "1.36", features = ["rt"] }
dunce.workspace = true

[dev-dependencies]
tf-tap.workspace = true

[lints]
workspace = true
