[package]
name = "termforge"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "termforge"
path = "src/main.rs"

[dependencies]
libterm = { path = "../../crates/libterm" }
renderer-dx12 = { path = "../../crates/renderer-dx12" }
tokio.workspace = true
uuid.workspace = true
anyhow.workspace = true
rstar = "0.12"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
windows.workspace = true
